// CSS Custom Property Generator
import { ScaleStep } from './types';

/**
 * Generate CSS custom properties for the typography scale
 */
export function generateCSSVariables(
  scaleSteps: ScaleStep[],
  customFont: string | null,
  customFontName: string | null,
  fontAxes: Record<string, number>
): string {
  const lines: string[] = [];

  lines.push(':root {');
  lines.push('  /* Typography Scale - Generated by Sovereign Scale */');
  lines.push('  /* https://github.com/sovereign-scale */');
  lines.push('');

  // Font family
  if (customFont && customFontName) {
    lines.push(`  /* Custom Font */`);
    lines.push(`  --font-family: "${customFontName}", system-ui, sans-serif;`);
    lines.push('');
  }

  // Font variation settings if custom axes are set
  const axisEntries = Object.entries(fontAxes);
  if (axisEntries.length > 0) {
    const axisString = axisEntries
      .map(([axis, value]) => `"${axis}" ${value}`)
      .join(', ');
    lines.push(`  /* Variable Font Axes */`);
    lines.push(`  --font-variation-settings: ${axisString};`);
    lines.push('');
  }

  // Scale steps
  lines.push('  /* Fluid Typography Scale */');
  scaleSteps.forEach((step) => {
    const varName = `--font-size-${step.name}`;
    lines.push(`  ${varName}: ${step.clampFormula};`);
  });

  lines.push('');
  lines.push('  /* Optical Sizes (for variable fonts with opsz axis) */');
  scaleSteps.forEach((step) => {
    const varName = `--optical-size-${step.name}`;
    lines.push(`  ${varName}: ${step.opticalSize};`);
  });

  lines.push('}');
  lines.push('');

  // Utility classes
  lines.push('/* Utility Classes */');
  scaleSteps.forEach((step) => {
    lines.push(`.text-${step.name} {`);
    lines.push(`  font-size: var(--font-size-${step.name});`);
    lines.push(`  font-variation-settings: "opsz" var(--optical-size-${step.name});`);
    lines.push('}');
    lines.push('');
  });

  return lines.join('\n');
}

/**
 * Generate a minimal CSS snippet for copy-paste
 */
export function generateMinimalCSS(scaleSteps: ScaleStep[]): string {
  const lines: string[] = [];

  lines.push(':root {');
  scaleSteps.forEach((step) => {
    lines.push(`  --font-size-${step.name}: ${step.clampFormula};`);
  });
  lines.push('}');

  return lines.join('\n');
}

/**
 * Generate Tailwind CSS config extension
 */
export function generateTailwindConfig(scaleSteps: ScaleStep[]): string {
  const lines: string[] = [];

  lines.push('// tailwind.config.js');
  lines.push('module.exports = {');
  lines.push('  theme: {');
  lines.push('    extend: {');
  lines.push('      fontSize: {');

  scaleSteps.forEach((step, index) => {
    const comma = index < scaleSteps.length - 1 ? ',' : '';
    lines.push(`        '${step.name}': '${step.clampFormula}'${comma}`);
  });

  lines.push('      }');
  lines.push('    }');
  lines.push('  }');
  lines.push('}');

  return lines.join('\n');
}

/**
 * Generate SCSS variables
 */
export function generateSCSS(scaleSteps: ScaleStep[]): string {
  const lines: string[] = [];

  lines.push('// Typography Scale - Generated by Sovereign Scale');
  lines.push('');

  scaleSteps.forEach((step) => {
    lines.push(`$font-size-${step.name}: ${step.clampFormula};`);
  });

  lines.push('');
  lines.push('// Mixin for applying scale with optical sizing');
  lines.push('@mixin fluid-text($step) {');
  lines.push('  font-size: var(--font-size-#{$step});');
  lines.push('  font-variation-settings: "opsz" var(--optical-size-#{$step});');
  lines.push('}');

  return lines.join('\n');
}

export type ExportFormat = 'css' | 'minimal' | 'tailwind' | 'scss';

export function generateExport(
  format: ExportFormat,
  scaleSteps: ScaleStep[],
  customFont: string | null = null,
  customFontName: string | null = null,
  fontAxes: Record<string, number> = {}
): string {
  switch (format) {
    case 'css':
      return generateCSSVariables(scaleSteps, customFont, customFontName, fontAxes);
    case 'minimal':
      return generateMinimalCSS(scaleSteps);
    case 'tailwind':
      return generateTailwindConfig(scaleSteps);
    case 'scss':
      return generateSCSS(scaleSteps);
    default:
      return generateCSSVariables(scaleSteps, customFont, customFontName, fontAxes);
  }
}
